packages:
  - agent
  - browser
  - database
  - engine
  - logger
  - mobile
  - website

allowBuilds:
  "@clerk/shared": true
  "@parcel/watcher": true
  "@prisma/engines": true
  esbuild: true
  lefthook: true
  msw: true
  prisma: true
  sharp: true
  workerd: true
